### PR TITLE
Add notify method to sealed promises

### PR DESCRIPTION
**Pull request by arturgorski**
Proposal for solving the bug #137

### CODE REVIEW

**Comment by ajaykodali** [comment]
Looking for this fix. We use assert.eventually all over the place and this currently not compatible with new Selenium WebDriver versions

**Comment by domenic** [comment]
Can't WebDriver just stop sealing its promises? I don't think we should include workarounds for every weird thing a promise library does.

**Comment by ajaykodali** [comment]
fyi, this issue is resolved with selenium-webdriver v2.52.0. Thanks.

**Comment by domenic** [comment]
Ah, thank goodness. I appreciate the update.

**Pull request closed without merging**
