### PR TITLE
Updated package.json peerDependencies for chai to ^2.1.2

### PR DESCRIPTION
**Pull request by BobbieBarker**
Hopefully this will clear up #108  issues.

### CODE REVIEW

**Comment by domenic** [comment]
This does not show that the tests pass with Chai 3. To show that, you need to update the dev dependenciez to 3 as a minimum.

**Comment by BobbieBarker** [comment]
You're right I slipped up. Give me a bit and I'll take care of it.

**Comment by keithamus** [comment]
The version string could easily be just `">= 2.1.2 < 4"` right?

**Comment by BobbieBarker** [comment]
Right now the build has four failing tests against chai 3.0.0 that seem to be isolated to the rejectedWith stuff. I'm not familiar with the code base so it's taking a wee bit more effort than I would like.

**Comment by BobbieBarker** [comment]
Also I don't personally use coffee script so I am having a hard time reading your unit tests.

**Comment by keithamus** [comment]
Hey @BobbieBarker, #110 solves this and supersedes your PR. Thanks for your efforts though, much appreciated!

**Comment by BobbieBarker** [comment]
No, Thank you @keithamus  for submitting the passing PR so I can get back to unit testing my code.

**Pull request closed without merging**
