### PR TITLE
Update for compat with chainable method overwriting

### PR DESCRIPTION
**Pull request by joshperry**

### CODE REVIEW

**Comment by domenic** [comment]
Tests? What does this fix?

**Comment by joshperry** [comment]
I didn't change or add functionality, I assumed the existing tests would suffice to ensure there was no change in that regard. I am happy to write some if you feel there is a need.

This fixes the code calling `addChainableMethod` to overwrite existing methods when chai has `overwriteChainableMethod` for that purpose. This makes it difficult to manage reentrancy in other plugins that also need to overwrite existing chainable methods.

Also, detecting chainable methods by the getters in a try/catch to see if they return a function is error prone if you don't know the preconditions that the getter expects. This instead looks at the chainable method registry that chai keeps.

**Comment by domenic** [comment]
If there's no change or add to functionality, then there's no reason to merge this. It sounds like there are changes, from your description; there need to be tests for that then.

**Comment by domenic** [comment]
Ping. Would love tests on this. I noticed from the referenced issue you seem to think I don't like you and am dead-set against this? I can assure you that's not the case.

**Comment by domenic** [comment]
Superceded by #94, which included tests.

**Pull request closed without merging**
